
dataset:
  repo_id: "xhaka3456/openarm_foldingtowel_260726"  # HuggingFace repo ID (본인 계정으로 변경)
  single_task: "folding mint white towel"  # 태스크 설명
  root: "~/openarm/src/openarm_lerobot/datasets/openarm_foldingtowel_260726"                    # 로컬 저장 경로 (null이면 HF 캐시 사용)
  fps: 30
  episode_time_s: 600                          # 에피소드당 녹화 시간 (초)
  reset_time_s: 1                                # 에피소드 간 리셋 대기 시간 (초)
  num_episodes: 10                               # 총 에피소드 수
  video: true                                    # 프레임을 비디오로 인코딩
  push_to_hub: true                             # true면 수집 완료 후 자동 업로드


display_data: true                               # Rerun 시각화 (카메라 + 관절값 그래프 실시간 표시)
resume: false                                    # 기존 데이터셋에 이어서 녹화

cameras:
  eye_right:          # 스테레오 좌
    type: "opencv"
    index: 2         # /dev/video 번호는 실제 연결 확인 후
    width: 1280
    height: 720
    fps: 30
    fourcc: "MJPG"   # 필수: 이거 없으면 YUYV로 열려 720p가 실제 10fps
  eye_left:         # 스테레오 우
    type: "opencv"
    index: 4
    width: 1280
    height: 720
    fps: 30
    fourcc: "MJPG"   # 필수: 이거 없으면 YUYV로 열려 720p가 실제 10fps


# ROS 2 토픽
topics:
  joint_states: "/joint_states"
  left_eef_pose: "/left_eef_pose"
  right_eef_pose: "/right_eef_pose"
  left_eef_delta: "/left_eef_delta"
  right_eef_delta: "/right_eef_delta"
  left_target_joint_positions: "/left_target_joint_positions"
  right_target_joint_positions: "/right_target_joint_positions"
  left_gripper: "/left_gripper_trigger"
  right_gripper: "/right_gripper_trigger"
  quest_x_button: "/quest_x_button"
  quest_rerecord: "/quest_rerecord"


